services:
  - type: web
    name: tripl
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
    plan: free
    healthCheckPath: /api/health
